Inputs:
  path: '~/Repos/VTAC_ML/data/combined_qpo_vt_with_GRB.parquet'
#  path: '/Users/jeremypalmerio/Repos/VTAC_ML/data/combined_qpo_vt_faint_case_with_GRB_with_flags.parquet'
  columns: ["MAGCAL_R0",
    "MAGCAL_B0",
    "MAGERR_R0",
    "MAGERR_B0",
    "MAGCAL_R1",
    "MAGCAL_B1",
    "MAGERR_R1",
    "MAGERR_B1",
    "MAGVAR_R1",
    "MAGVAR_B1",
#    "CASE",
    "EFLAG_B1"
    ]
  target_column: 'IS_GRB'
#  model: 'RFClassifier'
rfc:
  param_grid:
    'rfc__n_estimators': [ 100 ]
    'rfc__max_depth': [ 4 ]
    'rfc__min_samples_split': [ 2 ]
ada:
  param_grid:
    'ada__n_estimators': [ 100 ]  # Number of weak learners
    'ada__learning_rate': [ 0.1 ]  # Learning rate
    'ada__algorithm': [ 'SAMME' ]
Outputs:
  model:
    path:
  plot_correlation:
    flag: True
    path: 'output/corr_plots/'
